--
-- Author: 
-- Date: 2018-08-07 18:17:10
-- 跑得快工具类
local config ={
 [-20000]={key='inner_server',tip='服务器内部错误(-20000)',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20001]={key='in_scene',tip='已经在场景内',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20002]={key='scene_player_not_exist',tip='场景玩家不存在',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20003]={key='not_in_scene',tip='不在场景内',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20004]={key='basedatamgr_null',tip='BaseDataMgr 为空',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20005]={key='baseroomsetting_null',tip='房间配置表为空',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20006]={key='scene_null',tip='场景为空',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20007]={key='scnee_id_invalid',tip='场景ID不一致',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20008]={key='roomsetting_extend_invalid',tip='房间配置表扩展字段非法',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20009]={key='scene_game_setting_null',tip='场景游戏对应配置表为空',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20010]={key='roomsetting_gamekind_invalid',tip='房间配置表游戏类型非法',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20011]={key='in_scene_not_signup',tip='已进场景，未报名',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20012]={key='signuped_no_mate',tip='已报名未匹配',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-20013]={key='maintenance_please_wiat',tip='维护期间，请稍后再试',tip2='维护期间，请稍后再试',type=1,title='',note='场景公共',},
 [-20014]={key='not_in_room_game_time',tip='此房间还没到游戏时间',tip2='网络原因，请稍后再试',type=1,title='',note='场景公共',},
 [-22000]={key='signuped',tip='已经报名比赛，不能重复报名',tip2='已经报名比赛，不能重复报名',type=1,title='',note='超快赛',},
 [-22001]={key='in_cost_no_signup',tip='您当前处于比赛扣费阶段，不能重复报名比赛',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22002]={key='money_less_no_signup',tip='报名费不足，不能报名比赛',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22003]={key='fast_match_player_not_exist',tip='超快赛玩家不存在',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22004]={key='match_gameatomtypeid_invalid',tip='比赛信息不合法',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22005]={key='fast_match_cfg_null',tip='超快赛配置为空',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22006]={key='signup_condition_invalid',tip='比赛报名条件非法',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22007]={key='notify_hall_sub_signup_cost_fail',tip='通知大厅扣费失败',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22008]={key='roomtype_not_match_full',tip='房间类型不是满人赛',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22009]={key='in_cost_no_cancel_signup',tip='已进入比赛报名扣费阶段，不能退赛',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22010]={key='mated_no_cancel_signup',tip='已匹配，不能退赛',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22011]={key='match_begin_no_cancel',tip='比赛已开始了，不能退赛',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22012]={key='get_match_scene_data_error',tip='获取比赛场景数据失败',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22013]={key='signup_cost_unit_not_exist',tip='比赛报名扣费信息不存在',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22014]={key='signup_cost_no_forece_exit',tip='超快赛收费阶段，非法强退操作',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22015]={key='match_collect_not_signup',tip='收集状态阶段，不能重复报名比赛',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22016]={key='signup_extend_param_invalid',tip='比赛报名扩展参数非法',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-22017]={key='match_collect_not_cancel',tip='收集状态阶段，不能退赛',tip2='网络原因，请稍后再试',type=1,title='',note='超快赛',},
 [-24000]={key='room_cost_not_engough',tip='房费不足，不能进入',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24001]={key='roomtype_not_sys',tip='房间类型不是系统房',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24002]={key='sys_player_not_exist',tip='系统房玩家不存在',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24003]={key='sys_gameatomtypeid_invalid',tip='系统房信息不合法',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24004]={key='sys_entered',tip='已进入系统房，不能重复报名进入，未走重连流程',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24005]={key='sys_collect_not_enter',tip='收集状态阶段，不能重复进入',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24006]={key='sys_min_gold_coin',tip='系统房最小金币限制非法',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24007]={key='sys_exit_return_goldcoin',tip='强退返回金币到大厅途中，请勿重复操作',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24008]={key='sys_min_score_invalid',tip='系统房底分不合法',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 [-24009]={key='sys_max_score_gold',tip='系统房最大金币不合法',tip2='网络原因，请稍后再试',type=1,title='',note='系统房',},
 }
return config